name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "tests/a.txt,tests/b.txt"
        target: ${{ secrets.SSH_TARGET }}


#        host: ${{ secrets.SSH_HOST }}
#        username: ${{ secrets.SSH_USER }}
#        key: ${{ secrets.SSH_KEY }}
#        passphrase: ${{ secrets.SSH_PASSPHRASE }}
#        port: ${{ secrets.SSH_PORT }}
#        source: "tests/a.txt,tests/b.txt"
#        target: "test"
#        host: ${{ secrets.SSH_HOST }}
#        username: ${{ secrets.SSH_USER }}
#        password: ${{ secrets.SSH_PASSWORD }}
#        port: ${{ secrets.SSH_PORT }}
#        source: "tests/a.txt,tests/b.txt"
#        target: ${{ secrets.SSH_TARGET }}