name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "tests/a.txt,tests/b.txt"
        target: ${{ secrets.SSH_TARGET }}
#name: deploy
#
#on:
#  push:
#      branches:
#        - main
#  
#jobs:
#  deploy:
#    name: deployment1
#    runs-on: ubuntu-latest
#    steps:
#        - uses: actions/checkout@v2
#        - name: deploy to server
#          uses: appleboy/scp-action@master
#          with:
#            HOST: ${{secrets.SSH_HOST}}
#            PORT: ${{secrets.SSH_PORT}}
#            USERNAME: ${{secrets.SSH_USER}}
#            passowrd: ${{secrets.SSH_PASSWORD}}
#            source: "./src/*"
#            strip_components: 1
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY }} 
#          name: deploy with github
#          known_hosts: 'test'
#      - name: Adding Known Hosts
#        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
#      - name: rsync over ssh
#        run: rsync -avz ./src/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/
