name: Github Actions CI

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm ci
      - run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm ci
      - run: npm run build


#name: scp files
#on: [push]
#jobs:
#
#  build:
#    name: Linting
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/setup-node@v1
#      with:
#        node-version: 12
#    - run: npm ci
#    - run: npm run lint
#
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    - uses: actions/checkout@master
#      uses: appleboy/scp-action@master
#      with:
#        host: ${{ secrets.SSH_HOST }}
#        username: ${{ secrets.SSH_USER }}
#        key: ${{ secrets.SSH_KEY }}
#        port: ${{ secrets.SSH_PORT }}
#        passphrase: ${{ secrets.SSH_PASSPHRASE }}
#        source: "dist/*"
#        target: ${{ secrets.SSH_TARGET }}
