name: deploy

on:
  push:
      branches:
        - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          name: deploy with github
          known_hosts: 'test'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: testSSH
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} {{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
      - name: rsync over ssh
        run: rsync ./src/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:home/
